name: Kubernetes CD

on:
  push:
    branches:
      - develop
      - staging
      - main # For production

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo build & push

  deploy-dev-staging:
    needs: build-and-push
    if: github.ref_name == 'develop' || github.ref_name == 'staging'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo deploy dev

  deploy-prod:
    needs: deploy-dev-staging
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment:
      name: production
      url: MyUrl
    steps:
      - run: echo prod deploy
